package main

import (
	"context"
	"errors"
	"net/http"
	"os"
	"os/signal"
	"social/docs" // docs is generated by Swag CLI, you have to import it.
	"social/internal/auth"
	"social/internal/mailer"
	"social/internal/store"
	"syscall"
	"time"

	"fmt"
	"social/internal/store/cache"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"
	"go.uber.org/zap"
)

type application struct {
	config        config
	store         store.Storage
	cacheStorage  cache.Storage
	logger        *zap.SugaredLogger
	mailer        mailer.Client
	authenticator auth.Authenticator
}

type config struct {
	addr        string
	db          dbConfig
	env         string
	apiURL      string
	mail        mailConfig
	frontendURL string
	auth        authConfig
	redisCfg    redisConfig
}

type authConfig struct {
	basic basicConfig
	token tokenConfig
}

type basicConfig struct {
	user string
	pass string
}

type tokenConfig struct {
	secret string
	exp    time.Duration
	iss    string
}

type mailConfig struct {
	fromEmail string
	sendGrid  sendGridConfig
	exp       time.Duration
}

type redisConfig struct {
	addr    string
	pw      string
	db      int
	enabled bool
}

type sendGridConfig struct {
	apiKey string
}

type dbConfig struct {
	addr         string
	maxOpenConns int
	maxIdleConns int
	maxIdleTime  string //time.Duration
}

func (app *application) mount() http.Handler {
	// reference: https://github.com/go-chi/chi
	// Create a new chi router instance
	r := chi.NewRouter()

	r.Use(middleware.Logger)    // Log the start and end of each request
	r.Use(middleware.Recoverer) // Recover from panics and log the error
	r.Use(middleware.RealIP)    // Get the real IP address of the client
	r.Use(middleware.RequestID) // Generate a unique request ID for each request

	// Set a timeout value on the request context (ctx), that will signal
	// through ctx.Done() that the request has timed out and further
	// processing should be stopped.
	r.Use(middleware.Timeout(60 * time.Second))

	r.Route("/v1", func(r chi.Router) {
		// /v1/health
		r.With(app.BasicAuthMiddleware()).Get("/health", app.healthCheckHandler)

		docsURL := fmt.Sprintf("%s/swagger/doc.json", app.config.addr)
		r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL(docsURL)))

		// /v1/posts
		r.Route("/posts", func(r chi.Router) {
			r.Use(app.AuthTokenMiddleware) // Middleware to check if the user is authenticated
			r.Post("/", app.createPostsHandler)

			r.Route("/{postID}", func(r chi.Router) {
				r.Use(app.postContextMiddleware) // Middleware to extract postID from URL and set it in the context
				r.Get("/", app.getPostHandler)
				r.Delete("/", app.checkPostOwnership("admin", app.deletePostHandler))
				r.Patch("/", app.checkPostOwnership("moderator", app.updatePostHandler))
			})
		})

		// /v1/users
		r.Route("/users", func(r chi.Router) {

			r.Put("/activate/{token}", app.activateUserHandler) // Activate user account

			r.Route("/{userID}", func(r chi.Router) {
				r.Use(app.AuthTokenMiddleware) // Middleware to check if the user is authenticated
				// r.Use(app.userContextMiddleware) // Middleware to extract userID from URL and set it in the context

				r.Get("/", app.getUserHandler)

				r.Put("/follow", app.followUserHandler)
				r.Put("/unfollow", app.unfollowUserHandler)
			})

			// /v1/users/feed
			r.Group(func(r chi.Router) {
				r.Use(app.AuthTokenMiddleware) // Middleware to check if the user is authenticated
				r.Get("/feed", app.getUserFeedHandler)
			})
		})

		r.Route("/authentication", func(r chi.Router) {
			r.Post("/user", app.registerUserHandler)
			r.Post("/token", app.createTokenHandler)
		})
	})

	return r
}

func (app *application) run(mux http.Handler) error {

	// DOCS
	docs.SwaggerInfo.Version = version
	docs.SwaggerInfo.Host = app.config.apiURL
	docs.SwaggerInfo.BasePath = "/v1"

	srv := &http.Server{
		Addr:         app.config.addr,
		Handler:      mux,
		WriteTimeout: time.Second * 30, // Set a write timeout of 30 seconds
		ReadTimeout:  time.Second * 10, // Set a read timeout of 10 seconds
		IdleTimeout:  time.Minute,      // Set an idle timeout of 1 minute
	}

	shutdown := make(chan error)
	go func() {
		quit := make(chan os.Signal, 1)

		signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
		s := <-quit

		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()

		app.logger.Infow("Shutdown signal received", "signal", s.String())
		shutdown <- srv.Shutdown(ctx)
	}()

	app.logger.Infow("Server has started", "Addr", app.config.addr, "env", app.config.env)

	err := srv.ListenAndServe()
	if !errors.Is(err, http.ErrServerClosed) {
		return err
	}

	err = <-shutdown
	if err != nil {
		return err
	}

	app.logger.Infow("server has stopped", "addr", app.config.addr, "env", app.config.env)

	return nil
}
