basePath: /v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a what I am Learning in the Go Backend Course
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Backend Course API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    description: Authorization header with JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
